- name: Install nginx
  yum:
    name=nginx
    state=latest

- name: Start and Enable Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: True

- name: Replace nginx.conf
  template:
    src=roles/nginx/templates/nginx.conf
    dest=/etc/nginx/nginx.conf
  notify:
  - nginx restart

